plugins {
    id 'java-library'
    id 'io.qameta.allure' version '4.0.2'
}

repositories {
    mavenCentral()
}

def
        restAssuredVersion = '6.0.0',
        junitVersion = '6.0.3',
        slf4jVersion = '2.0.18',
        assertjVersion = '3.27.7',
        lombokVersion = '1.18.46',
        allureJunitVersion = '2.34.0',
        jacksonVersion = '2.21.2',
        allureRestAssuredVersion = '2.34.0',
        datafakerVersion = '2.5.4',
        ownerVersion = '1.0.12'

allure {
    version = "$allureJunitVersion"
    adapter {
        resultsDir.set(file("${projectDir}/allure-results"))
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion",
            "org.slf4j:slf4j-api:$slf4jVersion",
            "io.rest-assured:rest-assured:$restAssuredVersion",
            "org.assertj:assertj-core:$assertjVersion",
            "org.projectlombok:lombok:$lombokVersion",
            "io.qameta.allure:allure-junit5:$allureJunitVersion",
            "io.qameta.allure:allure-rest-assured:$allureRestAssuredVersion",
            "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion",
            "net.datafaker:datafaker:$datafakerVersion",
            "org.aeonbits.owner:owner:$ownerVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
    testCompileOnly "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperties(System.getProperties() as Map<String, ?>)
    systemProperty "allure.results.directory", "${projectDir}/allure-results"
    testLogging {
        lifecycle {
            events = ["started", "skipped", "failed", "standard_error", "standard_out"]
            exceptionFormat = "short"
        }
    }
}

tasks.register('positiveTests', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'PositiveTests'
    }
}

tasks.register('negativeTests', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'NegativeTests'
    }
}

tasks.register('getBookings', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'GetBookings'
    }
}

tasks.register('createBookings', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'CreateBookings'
    }
}

tasks.register('updateBookings', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'UpdateBookings'
    }
}

tasks.register('deleteBookings', Test) {
    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath
    useJUnitPlatform {
        includeTags 'DeleteBookings'
    }
}


